sudo: required
language: java
jdk:
- oraclejdk8
before_install:
- nvm install 4.2.6 && nvm use 4.2.6
- npm install gitbook-cli -g
script:
- cp deploy.sh ~/
- . ~/deploy.sh
after_success:
- echo Good Ending!
