sudo: required
language: scala
jdk:
- oraclejdk8
before_install:
- nvm install 4.2.6 && nvm use 4.2.6
- npm install gitbook-cli -g
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
- cp deploy.sh ~/
- . ~/deploy.sh
after_success:
- echo Good Ending!
